### ISSUE TITLE
Can't uninstall bubbles

### ISSUE THREAD

**Issue by Red1C3** [SonicMastr/godot#10]
I've built a very simple game, just an empty scene with a sprite for testing, it worked but when I try to uninstall it I get the following error "C2-17770-2" , I've built the game using Godot 3.5-rc5-vita1 Linux bin

**Comment by SonicMastr** [comment]
Send the param.sfo file

**Comment by RedDeadAlice** [comment]
[param.zip](https://github.com/SonicMastr/godot/files/9128658/param.zip)
There you go

**Comment by SonicMastr** [comment]
Ok. That confirms what I thought was happening. The Param.sfo is corrupted

One easy way to fix this at least would be to open godot again, export a VPK once (only on a new Godot start), open the VPK and copy that param.sfo manually to the directory on the vita. reboot the vita and then attempt to uninstall

**Comment by RedDeadAlice** [comment]
Ok I've tried the following: Open Godot, open the same project, export a VPK, extract it, replace the param.sfo in the Vita, attempt to uninstall, same error pops up, refresh LiveArea, attempt to uninstall, same error pops up, I've also tried turning off the "export with debug" option, it's all the same, is there a way to check if the param.sfo is corrupted myself?
