### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by Mosivic** [SonicMastr/godot#11]
Godot version:
3.5-rc5

OS/device including version:
Vita 3.68 HENkaku 
 
Issue description:
The installation of the exported vpk is successful, but when I open the game bubble, the game will be black for a few seconds and then flash back. I tried the export of the simplest scene as well.

**Comment by POtOSoftware** [comment]
Did you make sure to enable "Fallback to GLES2" in the project settings?

**Comment by Mosivic** [comment]
>yes i confirmed my settings are GLES2.

**Comment by Mosivic** [comment]
> Did you make sure to enable "Fallback to GLES2" in the project settings?

yes i confirmed my settings are GLES2.

**Comment by POtOSoftware** [comment]
I'm not sure if you mean that you've selected GLES2 as your project's video driver or not. But even if you have GLES2 selected as your project's video driver you have to enable "Fallback to GLES2" in your project settings

**Comment by Mosivic** [comment]
> I'm not sure if you mean that you've selected GLES2 as your project's video driver or not. But even if you have GLES2 selected as your project's video driver you have to enable "Fallback to GLES2" in your project settings

Well, the problem is caused by this reason, the problem has been solved, thank you!
