### ISSUE TITLE
macOS export isn't running as is.

### ISSUE THREAD

**Issue by danielkariv** [SonicMastr/godot#7]
The macOS export can't work as it delivered in Github. the fix I found is to run this commend: 'chmod +x Godot' inside MacOS folder:
<img width="660" alt="image" src="https://user-images.githubusercontent.com/38776931/179058806-3d600f97-ab9e-4f03-a4a2-943480a8e663.png">
After doing that, the app is running without problem.

**Comment by SonicMastr** [comment]
Yeah. I assumed I may have had to do that with an OSX machine instead of chmod-ing it in Linux like I did. If you would want to send an updated zip in an attachment so I can update the build in the release, it would appreciated. I have no OSX systems :P

**Comment by SonicMastr** [comment]
Updated. Thank you
