### ISSUE TITLE
0x8010113D

### ISSUE THREAD

**Issue by L1ghtingBolt** [SonicMastr/godot#8]
**Godot version:**
3.5
**OS/device including version:**
Windows 11
**Issue description:**
Package does not install and gives 8bit error even tho the images are 8bit
**Steps to reproduce:**
Build and install with VitaShell

EDIT: Images are in 4bit* that's the problem. pngquant can only reduce, so any tip on making the image 8bits?

**Comment by RedDeadAlice** [comment]
Have you tried using GIMP? it's FOSS, and I just made my images with it and built a VPK, it worked!, just make sure you make the images are 8-bit **indexed** , Adobe Photoshop should do the trick too if you have that

**Comment by SonicMastr** [comment]
This is simply a misuse of PNGquant. I recommend just using the PNGoo GUI

**Comment by L1ghtingBolt** [comment]
> This is simply a misuse of PNGquant. I recommend just using the PNGoo GUI

Thanks! I had the setting 256 in the command but didn't work. I solved it using Paint.NET to convert them and it worked. I thought I closed the issue.
