### ISSUE TITLE
Gyroscope/accelerometer sensor support

### ISSUE THREAD

**Issue by POtOSoftware** [SonicMastr/godot#9]
The Vita has a Gyroscope and accelerometer. Why not use them? The only reason it doesn't work here is because Godot only supports Gyro/accel on Android and iOS

**Comment by SonicMastr** [comment]
It simply wasn't added because there wasn't anything to test it with and it wasn't a priority. Same with networking. It will come

**Comment by SonicMastr** [comment]
Accidental close

**Comment by POtOSoftware** [comment]
Fair enough, all makes sense.

Another thing I'm curious about though: Are the long load times in 3D scenes due to Vita hardware limitations? Or is it something to do with the port itself? Because I notice that the levels load fairly quickly (sound will start playing and the game card activity light stops flashing) but it takes a little while longer until the scene actually appears on screen

**Comment by POtOSoftware** [comment]
Did the same thing... so that's what that button does

**Comment by POtOSoftware** [comment]
Did the same thing...
So that's what that button does

**Comment by SonicMastr** [comment]
> Fair enough, all makes sense.
> 
> Another thing I'm curious about though: Are the long load times in 3D scenes due to Vita hardware limitations? Or is it something to do with the port itself? Because I notice that the levels load fairly quickly (sound will start playing and the game card activity light stops flashing) but it takes a little while longer until the scene actually appears on screen

This is just caused by shader compilation. Godot's GLES2 backend does not have a shader cache, so this performance hitch will happen. The feature is only a part of the GLES3 backend atm.

**Comment by SonicMastr** [comment]
Feature added in 231af49
